# Generated by Django 4.0 on 2022-01-01 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name_plural': 'order status'},
        ),
        migrations.AlterModelTable(
            name='orderproduct',
            table='order_product',
        ),
    ]
