# Generated by Django 4.0 on 2022-01-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
